name: CI                # shows up in the Actions tab
on: [push, pull_request] # run for every branch push and PR

jobs:
  build:
    runs-on: ubuntu-latest         # free runner
    steps:
      - uses: actions/checkout@v3  # pull your code

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # pick the same version you use locally

      - run: pip install -r requirements.txt
      - run: pip install pytest flake8        # dev-time tools

      - run: pytest                         # ▶️ unit tests
      - run: flake8 src streamlit_app       # ⇢ style / lint